import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      // ponytail: manual 48-line CSS var map → auto-generate from M3 seed color when adding theme builder UI
      colors: {
        "on-background": "var(--color-on-background)",
        "primary": "var(--color-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-container": "var(--color-surface-container)",
        "outline-variant": "var(--color-outline-variant)",
        "on-error-container": "var(--color-on-error-container)",
        "surface": "var(--color-surface)",
        "primary-container": "var(--color-primary-container)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "error-container": "var(--color-error-container)",
        "on-primary": "var(--color-on-primary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary": "var(--color-tertiary)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-low": "var(--color-surface-container-low)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-container": "var(--color-on-primary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-error": "var(--color-on-error)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary-container": "var(--color-secondary-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "error": "var(--color-error)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary": "var(--color-on-tertiary)",
        "outline": "var(--color-outline)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "secondary": "var(--color-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "background": "var(--color-background)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "260px",
        "tabbar-height": "64px",
        gutter: "16px",
        base: "4px",
        "container-margin": "24px",
      },
      fontFamily: {
        display: ["var(--font-inter)", "sans-serif"],
        "numeric-data": ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "numeric-data": ["16px", { lineHeight: "1", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
